Fix documentation wrt. refractory period as variable
NeuronGroup(1, model='''refractory : second''', refractory='refractory')

yields:

SyntaxError: The name 'refractory' is used in the refractory mechanism  and should not be used as a variable name.

But

G = NeuronGroup(1, model='''ref : second''', refractory='ref')

works.