Failure to produce documentation with python3.11.
In [Debian Bug#1027936], Adrian Bunk noticed that the documentation
failed to be produced with python3.11 with the following symptom:

	Traceback (most recent call last):
	  File "/usr/lib/python3/dist-packages/sphinx/config.py", line 350, in eval_config_file
	    exec(code, namespace)
	  File "/<<PKGBUILDDIR>>/docs_sphinx/conf.py", line 71, in <module>
	    generate_examples.main(root_dir, target_dir)
	  File "/<<PKGBUILDDIR>>/debian/tmp/usr/lib/python3.11/dist-packages/brian2/sphinxext/generate_examples.py", line 72, in main
	    with codecs.open(fname, 'rU', encoding='utf-8') as f:
	         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "<frozen codecs>", line 906, in open
	ValueError: invalid mode: 'rUb'

This patch removes a couple of uses of unified newline "open"
invocations, which have no effect since the first version of python3.
This may cause changes of behavior with python2, but this interpreter
is unmaintained since 2020.

[Debian Bug#1027936]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1027936

Signed-off-by: Étienne Mollier <emollier@debian.org>